title: 'C-iTRACE-tracers'
description: 'Coarse resolution, ocean-only simulation from 22ka to present using the isotope-enabled ocean component of CESM1'
pangeo_forge_version: '0.9.0'
pangeo_notebook_version: '2022.06.02'
recipes:
  - id: citrace_tracer
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'University of Colorado Boulder'
      description: 'University of Colorado Boulder'
      roles:
        - producer
      url: https://sites.google.com/colorado.edu/citrace
    - name: 'University of Wisconsin-Madison'
      description: 'University of Wisconsin-Madison'
      roles:
        - producer
      url: https://sites.google.com/colorado.edu/citrace
    - name: 'Ohio State University'
      description: 'Ohio State University'
      roles:
        - producer
      url: https://sites.google.com/colorado.edu/citrace
    - name: 'UCAR/NCAR'
      description: 'University Corporation for Atmospheric Research/National Center for Atmospheric Research'
      roles:
        - curator
        - licensor
      url: https://gdex.ucar.edu/dataset/204_ajahn.html
  license: 'Creative Commons Attribution 4.0 International'
maintainers:
  - name: 'Jordan Landers'
    orcid: '0000-0001-9772-7617'
    github: jordanplanders
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
