title: "Global Precipitation Climatology Project"
description: >
  Global Precipitation Climatology Project (GPCP) Daily Version 1.3 gridded, merged ty
  satellite/gauge precipitation Climate data Record (CDR) from 1996 to present.
pangeo_forge_version: "0.8.3"
pangeo_notebook_version: "2022.06.02"
recipes:
  - id: gpcp
    object: "recipe:recipe"
provenance:
  providers:
    - name: "NOAA NCEI"
      description: "National Oceanographic & Atmospheric Administration National Centers for Environmental Information"
      roles:
        - host
        - licensor
      url: https://www.ncei.noaa.gov/products/global-precipitation-climatology-project
    - name: "University of Maryland"
      description: >
        University of Maryland College Park Earth System Science Interdisciplinary Center
        (ESSIC) and Cooperative Institute for Climate and Satellites (CICS)
      roles:
        - producer
      url: http://gpcp.umd.edu/
  license: "No constraints on data access or use."
maintainers:
  - name: "Ryan Abernathey"
    orcid: "0000-0001-5999-4917"
    github: rabernat
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
