# Name for dataset. User chosen.
title: 'NOAA Atmospheric Climate Data Records: Aerosol Optical Thickness'
# Description of dataset.  User chosen, roughly 1 sentence in length.
description: 'A collection of global daily 0.1 degree derived data from the PATMOS-x AVHRR level-2b channel 1 (0.63 micron) orbital clear-sky radiance, generated in cloud-free conditions during daytime over oceans.'
# Version of pangeo_forge_recipes library that was used
pangeo_forge_version: '0.9.2'
# The recipes section tells Pangeo Cloud where to find the recipes within your PR.
# Many recipe PRs will have just 1 recipe, in which case this section will look similar to the example below.
# If your PR contains multiple recipes, you may add additional elements to the list below.
recipes:
  # User chosen name for recipe. Likely similiar to dataset name, ~25 characters in length
  - id: noaa-atmosphere-climate-aot
    # The `object` below tells Pangeo Cloud specifically where your recipe instance(s) are located and uses the format <filename>:<object_name>
    # <filename> is name of .py file where the Python recipe object is defined.
    # For example, if <filename> is given as "recipe", Pangeo Cloud will expect a file named `recipe.py` to exist in your PR.
    # <object_name> is the name of the recipe object (i.e. Python class instance) _within_ the specified file.
    # For example, if you have defined `recipe = XarrayZarrRecipe(...)` within a file named `recipe.py`, then your  `object` below would be `"recipe:recipe"`
    object: 'recipe:recipe'
provenance:
  # Data provider object.  Follow STAC spec.
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object
  providers:
    - name: 'NOAA NCEI'
      description: 'National Oceanographic & Atmospheric Administration National Centers for Environmental Information'
      roles:
        - producer
        - licensor
      url: https://www.ncdc.noaa.gov/cdr/atmospheric/avhrr-aerosol-optical-thickness
  # This is a required field for provider. Follow STAC spec
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#license
  license: 'Open Data'
maintainers:
  # Information about recipe creator. name and github are required
  - name: 'Ryan Avery'
    orcid: '0000-0001-7392-1474'
    github: rbavery
# The specific bakery (i.e. cloud infrastructure) that your recipe will run on.
# Available bakeries can be found on the Pangeo Forge website https://pangeo-forge.org/dashboard/bakeries
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
