title: 'GPM IMERG Final Precipitation L3 1 day 0.1 degree x 0.1 degree V07 (GPM_3IMERGDF) at GES DISC'
description: 'This dataset is the GPM Level 3 IMERG  *Final* Daily  10 x 10 km (GPM_3IMERGDF) derived from the half-hourly GPM_3IMERGHH.  The derived result represents the Final estimate of the daily mean precipitation rate in mm/day.'
pangeo_forge_version: '0.9.2'
recipes:
  - id: 'GPM_3IMERGDF.07'
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'NASA/GSFC/SED/ESD/GCDC/GESDISC'
      description: 'NASA/GSFC/SED/ESD/GCDC/GESDISC'
      roles:
        - producer
        - licensor
      url: 'https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGDF_07/summary'
  license: 'Open Data'
maintainers:
  - name: 'Development Seed'
    github: developmentseed
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
