title: "TerraClimate Monthly Surface Dataset"
description: "High-resolution monthly climate and climatic water balance dataset"
pangeo_forge_version: "0.5.0"
pangeo_notebook_version: "2021.07.17"
recipes:
  - id: terraclimate
    object: "recipe:recipe"
provenance:
  providers:
    - name: "Climatology Lab"
      description: "Climatology Lab at University of California Merced (http://www.climatologylab.org/)"
      roles:
        - producer
        - licensor
      url: http://www.climatologylab.org/terraclimate.html
  license: "CC-0-1.0"
maintainers:
  - name: "Raphael Hagen"
    orcid: "0000-0003-1994-1153"
    github: norlandrhagen
bakery:
  id: "devseed.bakery.development.aws.us-west-2"
  target: pangeo-forge-aws-bakery-flowcachebucketdasktest4-10neo67y7a924
  resources:
    memory: 4096
    cpu: 1024
