title: "SWOT-AdAC data (HYCOM25)"
description: "HYCOM25 regional data for SWOT-AdAC Xovers"
pangeo_forge_version: "0.0.1"  # do we need a separate spec version
recipes:
  - id: swot-adac-hycom25_surf
    module: recipe_01_surf.py  # the module where to find the recipe
    name: recipe_01_surf  # the name of the object to import
provenance:
  providers:
    - name: "Brian Arbic"
      description: "Earth and Environmental Science, University of Michigan"
      roles:
        - producer
        - licensor
      url: https://github.com/roxyboy/SWOT-AdAC-ocean-model-intercomparison
  license: "CC-BY-4.0"
maintainers:
  - name: "Takaya Uchida"
    orcid: "0000-0002-8654-6009"
    github: roxyboy
bakeries:
  - id: "pangeo-aws-west-1"  # must come from a valid list of bakeries
