title: "SWOT-AdAC data (INALT60)"
description: "INALT60 regional data for SWOT-AdAC Xovers"
pangeo_forge_version: "0.0.1"  # do we need a separate spec version
recipes:
  - id: inalt60_surf_ocean
    object: "recipe:"
    module: recipes.py  # the module where to find the recipe
    name: recipes  # the name of the object to import
  - id: inalt60_surf_flux
    object: "recipe:"
    module: recipe_inalt60.py
    name: recipe_inalt60
  - id: inalt60_int_ocean
    object: "recipe:"
    module: recipe_inalt60.py
    name: recipe_inalt60
provenance:
  providers:
    - name: "GEOMAR"
      description: "GEOMAR Helmholtz Centre for Ocean Research Kiel"
      roles:
        - producer
        - licensor
      url: https://github.com/roxyboy/SWOT-AdAC-ocean-model-intercomparison
  license: "CC-BY-4.0"
maintainers:
  - name: "Rene Schubert"
    orcid: "0000-0003-1118-3968"
    github: reneschubert
bakeries:
  - id: "pangeo-aws-west-1"  # must come from a valid list of bakeries
