title: 'RCMS1SIM'
description: 'RADARSAT Constellation Mission / Sentinel-1 Sea Ice Motion (RCMS1SIM) coarse-grid (RCMS1SIM_LR: 25km EASE1) and fine-grid (RCMS1SIM_HR: 6.25km EASE2) data available from the Climate Research Division (CRD)'
pangeo_forge_version: '0.9.4'
recipes:
  - id: rcms1sim_lr
    object: 'recipe_lr:recipe'
  - id: rcms1sim_hr
    object: 'recipe_hr:recipe'
provenance:
  providers:
    - name: 'ECCC'
      description: 'Environment and Climate Change Canada'
      roles:
        - producer
        - processor
        - host
      url: https://catalogue.ec.gc.ca/geonetwork/srv/eng/catalog.search#/metadata/09ab22c4-e211-4d23-afe6-9e7aa6831c62
    - name: 'Government of Canada'
      description: 'Government of Canada'
      roles:
        - licensor
      url: https://open.canada.ca/data/en/dataset/22aa3b41-425f-4f67-9747-f097c00e3eb1
  license: OGL-Canada-2.0
maintainers:
  - name: 'Mike Brady'
    orcid: 0000-0001-8263-0951
    github: m9brady
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
