# Name for dataset. User chosen.
title: 'CMIP6 GCMs downscaled using WRF'
description: 'Downscaling of CMIP6 GCMs conducted at UCLA for the western US over 45km and 9km grid-spacing, and over California and Wyoming for 3km grid-spacing in some cases.'

# The recipes section tells Pangeo Cloud where to find the recipes within your PR.
# Many recipe PRs will have just 1 recipe, in which case this section will look similar to the example below.
# If your PR contains multiple recipes, you may add additional elements to the list below.
recipes:
  # User chosen name for recipe. Likely similiar to dataset name, ~25 characters in length
  - id: cmip6-wrf-wus
    # The `object` below tells Pangeo Cloud specifically where your recipe instance(s) are located and uses the format <filename>:<object_name>
    # <filename> is name of .py file where the Python recipe object is defined.
    # For example, if <filename> is given as "recipe", Pangeo Cloud will expect a file named `recipe.py` to exist in your PR.
    # <object_name> is the name of the recipe object (i.e. Python class instance) _within_ the specified file.
    # For example, if you have defined `recipe = XarrayZarrRecipe(...)` within a file named `recipe.py`, then your  `object` below would be `"recipe:recipe"`
    object: 'recipe:recipe'
provenance:
  # Data provider object.  Follow STAC spec.
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object
  providers:
    - name: 'UCLA Center for Climate Science'
      description: 'University of California, Los Angeles Center for Climate Science'
      roles:
        - producer
        - licensor
	- processor
      url: https://dept.atmos.ucla.edu/alexhall/downscaling-cmip6
    - name: 'AWS'
      description: 'AWS Sustainability Data Initiative'
      roles:
        - host
      url: https://registry.opendata.aws/wrf-cmip6/
  # This is a required field for provider. Follow STAC spec
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#license
  license: 'CC BY-SA 4.0'
maintainers:
  # Information about recipe creator. name and github are required
  - name: 'Naomi Goldenson'
    orcid: '0000-0003-0656-4168'
    github: thenaomig

bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
