title: 'NWM-2.1-grid1km-LDAS'
description: 
  LDAS variables at 3-hourly intervals from the US National Water Model Version 2.1 Retrospective (1980-). There are 21 LDAS variables including soil moisture, rain, snow, evapotranspiration
pangeo_forge_version: '0.9.0'
pangeo_notebook_version: '2022.07.13'
recipes:
  - id: NWM-2.1-grid1km-LDAS
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'NOAA Office of Water Prediction'
      description: 'US NOAA OWP'
      roles:
        - provider
        - licensor
      url: https://water.noaa.gov/about/nwm
  license: 'CC0'
maintainers:
  - name: 'Rich Signell'
    orcid: '0000-0003-0682-9613'
    github: rsignell
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
