title: "NOAA Optimum Interpolated SST"
description: "1/4 degree daily gap filled sea surface temperature (SST)"
pangeo_forge_version: "0.6.2"
recipes:
  - id: noaa-oisst-avhrr-only
    object: "recipe:recipe"
provenance:
  providers:
    - name: "NOAA NCEI"
      description: "National Oceanographic & Atmospheric Administration National Centers for Environmental Information"
      roles:
        - producer
        - licensor
      url: https://www.ncdc.noaa.gov/oisst
  license: "CC-BY-4.0"
maintainers:
  - name: "Viet Nguyen"
    orcid: "0000-0001-8994-4558"
    github: vietnguyengit
bakery:
  id: "pangeo-ldeo-nsf-earthcube"