title: "Integrated Multi-satellite Retrievals for GPM"
description: "Integrated Multi-satellite Retrievals Global Precipition Model (GPM), every half hour, final product. Analysis-ready Zarr datasets derived from NASA HDF5"
pangeo_forge_version: "0.5.0"
pangeo_notebook_version: "2021.07.17"
recipes:
  - id: gpm-imerge-hhr
    object: "recipe:recipe"
provenance:
  providers:
    - name: "NASA PPS"
      description: "National Aeronautics and Space Administration Precipitation Processing Center"
      roles:
        - producer
        - licensor
      url: https://gpm.nasa.gov
  license: "Public Domain"
maintainers:
  - name: "Alex Mandel"
    orcid: "0000-0003-2024-6801"
    github: wildintellect
bakery:
  id: "devseed.bakery.development.aws.us-west-2" # must come from a valid list of bakeries
  target: pangeo-forge-aws-bakery-flowcachebucketdasktest4-10neo67y7a924
  resources:
    memory: 4096
    cpu: 1024
