name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          commands: run-recipe-test
          permission: maintain
          issue-type: pull-request
